//
// RelationsTex.swift
// Generated by Step_8_tex
//

import Foundation

struct RelationsTex {
   static var zeroRelations: [[String]] {
       let (n1, n2, n3) = (PathAlg.n1, PathAlg.n2, PathAlg.n3)
       let c12_n3_1 = n3 == 1 ? [] : (0 ..< n3 - 1).map { _ in "c12" }
       let c23_n1_1 = n1 == 1 ? [] : (0 ..< n1 - 1).map { _ in "c23" }
       let c31_n2_1 = n2 == 1 ? [] : (0 ..< n2 - 1).map { _ in "c31" }
       var relations: [[String]] = []
       relations += [ ["", "0"] ] // 0
       relations += [
           ["c12", "c23"], ["c23", "c31"], ["c12", "c31"],
           c12_n3_1 + ["c12", "c12"], c23_n1_1 + ["c23", "c23"], c31_n2_1 + ["c31", "c31"],
       ]
       relations += [ ["", "1"] ] // 1
       relations += [ ["c12", "z1"], ["c23", "z1"], ["c31", "z1"] ]
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["c12", "w23"], c23_n1_1 + ["c23", "w23"], ["c31", "w23"]  ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["c12", "w31"], ["c23", "w31"], c31_n2_1 + ["c31", "w31"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ c12_n3_1 + ["c12", "w12"], ["c23", "w12"], ["c31", "w12"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ c12_n3_1 + ["x1"], ["c23", "x1"], ["c31", "x1"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["c12", "x3"], ["c23", "x3"], c31_n2_1 + ["x3"] ]
       }
       relations += [ ["", "N1"] ]; if true {
           relations += [ c12_n3_1 + ["c12", "w"], c23_n1_1 + ["c23", "w"], c31_n2_1 + ["c31", "w"] ]
       }
       relations += [ ["", "2"] ] // 2
       relations += [
           ["c23", "x12"], ["c31", "x12"], ["c12", "x23"], ["c31", "x23"], ["c12", "x31"], ["c23", "x31"],
           ["z1", "z1"],
           ["c12", "u1"], ["c23", "u1"], ["c31", "u1"], ["c12", "u2"], ["c23", "u2"], ["c31", "u2"],
       ]
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["c12", "q"], ["c23", "q"], ["c31", "q"], ["z1", "w23"], ["w23", "w23"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["z1", "x1"],  ["w23", "x1"], ["x1", "x1"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["z1", "x3"], ["w23", "x3"], ["x1", "x3"], ["x3", "x3"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ c23_n1_1 + ["c23", "x23"], ["z1", "w31"], ["w23", "w31"], ["w31", "w31"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ c12_n3_1 + ["c12", "x12"], ["z1", "w12"], ["w23", "w12"], ["w31", "w12"], ["w12", "w12"] ]
       }
       relations += [ ["", "n2N3"] ]; if true {
           relations += [ ["w31", "x1"] ]
       }
       relations += [ ["", "N1"] ]; if true {
           relations += [ ["w", "w"] ]
       }
       relations += [ ["", "N2"] ]; if true {
           relations += [ c23_n1_1 + ["x23"], c31_n2_1 + ["x31"] ]
       }
       relations += [ ["", "N3"] ]; if true {
           relations += [ c12_n3_1 + ["x12"] ]
       }
       relations += [ ["", "3"] ] // 3
       relations += [ ["z1", "x12"], ["z1", "x23"], ["z1", "x31"] ]
       relations += [ ["", "n1"] ]; if true {
           relations += [
               ["z1", "q"], ["w23", "x12"], ["w23", "x31"], ["w23", "u1"], ["w23", "q"],
               ["c12", "w23_h"], c23_n1_1 + ["c23", "w23_h"], ["c31", "w23_h"]
           ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [
               ["x1", "x23"], ["x1", "x31"], ["x1", "u1"], ["x1", "u2"], ["x1", "q"],
               c12_n3_1 + ["x1_h"], ["c23", "x1_h"], ["c31", "x1_h"]
           ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [
               ["c12", "w31_h"], ["c23", "w31_h"], c31_n2_1 + ["c31", "w31_h"],
               ["w31", "x12"], ["w31", "x23"], ["w31", "u1"], ["w31", "q"]
           ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [
               c12_n3_1 + ["c12", "w12_h"], ["c23", "w12_h"], ["c31", "w12_h"],
               ["w12", "x23"], ["w12", "x31"], ["w12", "u1"], ["w12", "q"],
           ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [
               ["c12", "x3_h"], ["c23", "x3_h"], c31_n2_1 + ["x3_h"],
               ["x3", "x12"], ["x3", "x23"], ["x3", "u1"], ["x3", "u2"], ["x3", "q"],
           ]
       }
       relations += [ ["", "N1"] ]; if true {
           relations += [ ["w", "u1"] ]
       }
       relations += [ ["", "4"] ] // 4
       relations += [
           ["x12", "u1"], ["x23", "u1"], ["x31", "u1"], ["x12", "u2"], ["x23", "u2"], ["x31", "u2"],
           ["x12", "x23"], ["x23", "x31"], ["x12", "x31"], ["u1", "u1"], ["u2", "u2"], ["u1", "u2"]
       ]
       relations += [ ["", "N1"] ]; if true {
           relations += [c23_n1_1 + ["c23", "e"]]
       }
       relations += [ ["", "N2"] ]; if true {
           relations += [ c31_n2_1 + ["c31", "e"] ]
       }
       relations += [ ["", "N3"] ]; if true {
           relations += [ c12_n3_1 + ["c12", "e"] ]
       }
       relations += [ ["", "n1"] ]; if true {
           relations += [
               ["z1", "w23_h"], ["w23", "w23_h"],
               ["x12", "q"], ["x23", "q"], ["x31", "q"], ["u1", "q"], ["u2", "q"], ["q", "q"]
           ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["z1", "x1_h"], ["w23", "x1_h"], ["x1", "w23_h"], ["x1", "x1_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["z1", "w31_h"], ["w23", "w31_h"], ["w31", "w23_h"], ["w31", "w31_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [
               ["z1", "w12_h"], ["w23", "w12_h"], ["w31", "w12_h"], ["w12", "w23_h"], ["w12", "w31_h"], ["w12", "w12_h"]
           ]
       }
       relations += [ ["", "n2N3"] ]; if true {
           relations += [ ["w31", "x1_h"], ["x1", "w31_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [
               ["z1", "x3_h"], ["w23", "x3_h"], ["x1", "x3_h"], ["x3", "w23_h"], ["x3", "x1_h"], ["x3", "x3_h"]
           ]
       }
       relations += [ ["", "5"] ] // 5
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["w23_h", "x12"], ["w23_h", "x31"], ["w23_h", "u1"], ["w23_h", "u2"], ["w23_h", "q"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["x1_h", "x23"], ["x1_h", "x31"], ["x1_h", "u1"], ["x1_h", "u2"], ["x1_h", "q"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["w31_h", "x12"], ["w31_h", "x23"], ["w31_h", "u1"], ["w31_h", "u2"], ["w31_h", "q"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ ["w12_h", "x23"], ["w12_h", "x31"], ["w12_h", "u1"], ["w12_h", "u2"], ["w12_h", "q"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["x3_h", "x12"], ["x3_h", "x23"], ["x3_h", "u1"], ["x3_h", "u2"], ["x3_h", "q"] ]
       }
       relations += [ ["", "6"] ] // 6
       relations += [
           ["e", "u1"], ["e", "u2"],
           ["c12", "e1_h"], ["c23", "e1_h"], ["c31", "e1_h"], ["c12", "e2_h"], ["c23", "e2_h"], ["c31", "e2_h"]
       ]
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["w23_h", "w23_h"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["w23_h", "x1_h"], ["x1_h", "x1_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["w23_h", "x3_h"], ["x1_h", "x3_h"], ["x3_h", "x3_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["w23_h", "w31_h"], ["w31_h", "w31_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ ["w23_h", "w12_h"], ["w31_h", "w12_h"], ["w12_h", "w12_h"] ]
       }
       relations += [ ["", "n2N3"] ]; if true {
           relations += [ ["w31_h", "x1_h"] ]
       }
       relations += [ ["", "7"] ] // 7
       relations += [ ["", "n1"] ]; if true {
           relations += [
               ["w23", "e1_h"],
               ["c12", "u1_h"], ["c23", "u1_h"], ["c31", "u1_h"], ["c12", "u2_h"], ["c23", "u2_h"], ["c31", "u2_h"]
           ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["x1", "e1_h"], ["x1", "e2_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["x3", "e1_h"], ["x3", "e2_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["w31", "e1_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ ["w12", "e1_h"] ]
       }
       relations += [ ["", "8"] ] // 8
       relations += [
           ["e1_h", "x12"], ["e1_h", "x23"], ["e1_h", "x31"], ["e2_h", "x12"], ["e2_h", "x23"], ["e2_h", "x31"],
           ["e2_h", "u1"], ["e1_h", "u2"]
       ]
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["w23", "u1_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [  ["w31", "u1_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [  ["w12", "u1_h"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["x1", "u1_h"], ["x1", "u2_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["x3", "u1_h"], ["x3", "u2_h"] ]
       }
       relations += [ ["", "9"] ] // 9
       relations += [ ["", "n1"] ]; if true {
           relations += [
               ["x12", "u1_h"], ["x12", "u2_h"], ["x23", "u1_h"], ["x23", "u2_h"], ["x31", "u1_h"], ["x31", "u2_h"],
               ["u1", "u1_h"], ["u1", "u2_h"], ["u2", "u1_h"], ["u2", "u2_h"], ["u1_h", "q"], ["u2_h", "q"],
               ["w23_h", "e1_h"], ["w23_h", "e2_h"]
           ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["x1_h", "e1_h"], ["x1_h", "e2_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["x3_h", "e1_h"], ["x3_h", "e2_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["w31_h", "e1_h"], ["w31_h", "e2_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ ["w12_h", "e1_h"], ["w12_h", "e2_h"] ]
       }
       relations += [ ["", "10"] ] // 10
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["w23_h", "u1_h"], ["w23_h", "u2_h"] ]
       }
       relations += [ ["", "n1N3"] ]; if true {
           relations += [ ["x1_h", "u1_h"], ["x1_h", "u2_h"] ]
       }
       relations += [ ["", "n1N2"] ]; if true {
           relations += [ ["x3_h", "u1_h"], ["x3_h", "u2_h"] ]
       }
       relations += [ ["", "n2"] ]; if true {
           relations += [ ["w31_h", "u1_h"], ["w31_h", "u2_h"] ]
       }
       relations += [ ["", "n3"] ]; if true {
           relations += [ ["w12_h", "u1_h"], ["w12_h", "u2_h"] ]
       }
       relations += [ ["", "12"] ] // 12
       relations += [ ["", "N>3"] ]; if true {
           relations += [ ["e1_h", "e2_h"] ]
       }
       relations += [ ["", "13"] ] // 13
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["e1_h", "u2_h"], ["e2_h", "u1_h"] ]
       }
       relations += [ ["", "14"] ] // 14
       relations += [ ["", "n1"] ]; if true {
           relations += [ ["u1_h", "u1_h"], ["u1_h", "u2_h"], ["u2_h", "u2_h"] ]
       }
       return relations
   }

   static var relations: [([String], [String], String, Int)] {
       let (n1, n2, n3) = (PathAlg.n1, PathAlg.n2, PathAlg.n3)
       //let c12_n3_1 = n3 == 1 ? [] : (0 ..< n3 - 1).map { _ in "c12" }
       let c23_n1_1 = n1 == 1 ? [] : (0 ..< n1 - 1).map { _ in "c23" }
       let c31_n2_1 = n2 == 1 ? [] : (0 ..< n2 - 1).map { _ in "c31" }
       var relations: [([String], [String], String, Int)] = []
       relations += [ (["", "2"], [], "", 0)] // 2
       relations += [ (["", "n2N3"], [], "", 0)]; if true {
           relations += [ (c31_n2_1 + ["x31"], c23_n1_1 + ["x23"], "-1", -1) ]
       }
       relations += [ (["", "3"], [], "", 0)] // 3
       relations += [ (["", "n1"], [], "", 0)]; if true {
           relations += [
               (["w23", "x23"], ["c23", "w23_h"], "-1", -1),
               (["w23", "u2"], ["z1", "u2"], "1", 1)
           ]
       }
       relations += [ (["", "n1N3"], [], "", 0)]; if true {
           relations += [ (["x1", "x12"], ["c12", "x1_h"], "-1", -1) ]
       }
       relations += [ (["", "n2"], [], "", 0)]; if true {
           relations += [
               (["w31", "x31"], ["c31", "w31_h"], "-1", -1),
               (["w31", "u2"], ["z1", "u2"], "1", 1)
           ]
       }
       relations += [ (["", "n3"], [], "", 0)]; if true {
           relations += [
               (["w12", "x12"], ["c12", "w12_h"], "-1", -1),
               (["w12", "u2"], ["z1", "u2"], "1", 1)
           ]
       }
       relations += [ (["", "n1N2"], [], "", 0)]; if true {
           relations += [ (["x3", "x31"], ["c31", "x3_h"], "-1", -1) ]
       }
       relations += [ (["", "N1"], [], "", 0)]; if true {
           relations += [ (["w", "u2"], ["z1", "u2"], "(n1*n2+n2*n3+n3*n1)", n1 * n2 + n2 * n3 + n3 * n1) ]
       }
       relations += [ (["", "4"], [], "", 0)] // 4
       relations += [
           (["x12", "x12"], ["c12", "c12", "e"], "-1", -1),
           (["x23", "x23"], ["c23", "c23", "e"], "-1", -1),
           (["x31", "x31"], ["c31", "c31", "e"], "-1", -1)
       ]
       relations += [ (["", "5"], [], "", 0)] // 5
       relations += [ (["", "n1"], [], "", 0)]; if true {
           relations += [ (["w23_h", "x23"], ["c23", "w23", "e"], "1", 1) ]
       }
       relations += [ (["", "n1N3"], [], "", 0)]; if true {
           relations += [ (["x1_h", "x12"], ["c12", "x1", "e"], "1", 1) ]
       }
       relations += [ (["", "n1N2"], [], "", 0)]; if true {
           relations += [ (["x3_h", "x31"], ["c31", "x3", "e"], "1", 1) ]
       }
       relations += [ (["", "n2"], [], "", 0)]; if true {
           relations += [ (["w31_h", "x31"], ["c31", "w31", "e"], "1", 1) ]
       }
       relations += [ (["", "n3"], [], "", 0)]; if true {
           relations += [ (["w12_h", "x12"], ["c12", "w12", "e"], "1", 1) ]
       }
       relations += [ (["", "7"], [], "", 0)] // 7
       relations += [ (["", "n1"], [], "", 0)]; if true {
           relations += [ (["w23", "e2_h"], ["z1", "e2_h"], "1", 1) ]
       }
       relations += [ (["", "n2"], [], "", 0)]; if true {
           relations += [ (["w31", "e2_h"], ["z1", "e2_h"], "1", 1) ]
       }
       relations += [ (["", "n3"], [], "", 0)]; if true {
           relations += [ (["w12", "e2_h"], ["z1", "e2_h"], "1", 1) ]
       }
       relations += [ (["", "8"], [], "", 0)] // 8
       relations += [ (["", "n1"], [], "", 0)]; if true {
           relations += [
               (["w23", "u2_h"], ["z1", "u2_h"], "1", 1),
               (["e1_h", "q"], ["z1", "u1_h"], "-1", -1),
               (["e2_h", "q"], ["z1", "u2_h"], "1", 1)
           ]
       }
       relations += [ (["", "n2"], [], "", 0)]; if true {
           relations += [ (["w31", "u2_h"], ["z1", "u2_h"], "1", 1) ]
       }
       relations += [ (["", "n3"], [], "", 0)]; if true {
           relations += [ (["w12", "u2_h"], ["z1", "u2_h"], "1", 1) ]
       }
       relations += [ (["", "12"], [], "", 0)] // 12
       relations += [ (["", "N=3"], [], "", 0)]; if true {
           relations += [ (["e1_h", "e2_h"], ["e", "e", "e"], "", 1) ]
       }
       return relations
   }

   static var sumRelations: [([String], Int, [String], Int, [String])] {
       let (n1, n2, n3) = (PathAlg.n1, PathAlg.n2, PathAlg.n3)
       let c12_n3_1 = n3 == 1 ? [] : (0 ..< n3 - 1).map { _ in "c12" }
       let c23_n1_1 = n1 == 1 ? [] : (0 ..< n1 - 1).map { _ in "c23" }
       let c31_n2_1 = n2 == 1 ? [] : (0 ..< n2 - 1).map { _ in "c31" }
       return [ (c31_n2_1 + ["x31"], -1, c12_n3_1 + ["x12"], -1, c23_n1_1 + ["x23"]) ]
   }
}
